// <auto-generated />
using System;
using HomeNest.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace HomeNest.Migrations
{
    [DbContext(typeof(HomeNestDbContext))]
    partial class HomeNestDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.0");

            modelBuilder.Entity("HomeNest.Data.Models.ContactMessage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ContactMessages");
                });

            modelBuilder.Entity("HomeNest.Data.Models.Favorite", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("PropertyId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("UserId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("PropertyId");

                    b.HasIndex("UserId", "PropertyId")
                        .IsUnique();

                    b.ToTable("Favorites");
                });

            modelBuilder.Entity("HomeNest.Data.Models.NewsletterSubscriber", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SubscribedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("NewsletterSubscribers");
                });

            modelBuilder.Entity("HomeNest.Data.Models.Property", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Area")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("District")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Features")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Floor")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Furnished")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Image")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int?>("OwnerId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Price")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PriceUnit")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rooms")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OwnerId");

                    b.ToTable("Properties");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Area = 80,
                            CreatedAt = new DateTime(2026, 5, 5, 9, 43, 34, 735, DateTimeKind.Utc).AddTicks(7469),
                            Description = "Отдава се апартамент под наем в район Приморски, гр.Варна",
                            District = "Приморски",
                            Features = "3 стаен,Обзаведен,80 кв.м",
                            Floor = 3,
                            Furnished = true,
                            Image = "images/property-offer-1.jpg",
                            Price = 550,
                            PriceUnit = "/ месец",
                            Rooms = 3,
                            Title = "Апартамент",
                            Type = "3-стаен"
                        },
                        new
                        {
                            Id = 2,
                            Area = 45,
                            CreatedAt = new DateTime(2026, 5, 5, 9, 43, 34, 735, DateTimeKind.Utc).AddTicks(9113),
                            Description = "Уютно студио в центъра на Варна, близо до Морската градина",
                            District = "Център",
                            Features = "Студио,Обзаведен,45 кв.м",
                            Floor = 2,
                            Furnished = true,
                            Image = "images/property-offer-2.jpg",
                            Price = 350,
                            PriceUnit = "/ месец",
                            Rooms = 1,
                            Title = "Студио",
                            Type = "Студио"
                        },
                        new
                        {
                            Id = 3,
                            Area = 180,
                            CreatedAt = new DateTime(2026, 5, 5, 9, 43, 34, 735, DateTimeKind.Utc).AddTicks(9118),
                            Description = "Просторна семейна къща в тих квартал с градина",
                            District = "Владиславово",
                            Features = "5 стаен,Необзаведен,180 кв.м",
                            Floor = 2,
                            Furnished = false,
                            Image = "images/property-offer-3.jpg",
                            Price = 1200,
                            PriceUnit = "/ месец",
                            Rooms = 5,
                            Title = "Къща",
                            Type = "Къща"
                        },
                        new
                        {
                            Id = 4,
                            Area = 140,
                            CreatedAt = new DateTime(2026, 5, 5, 9, 43, 34, 735, DateTimeKind.Utc).AddTicks(9122),
                            Description = "Луксозен мезонет с панорамна гледка към морето",
                            District = "Приморски",
                            Features = "4 стаен,Обзаведен,140 кв.м",
                            Floor = 6,
                            Furnished = true,
                            Image = "images/property-1.jpg",
                            Price = 950,
                            PriceUnit = "/ месец",
                            Rooms = 4,
                            Title = "Мезонет",
                            Type = "Мезонет"
                        },
                        new
                        {
                            Id = 5,
                            Area = 65,
                            CreatedAt = new DateTime(2026, 5, 5, 9, 43, 34, 735, DateTimeKind.Utc).AddTicks(9126),
                            Description = "Приятен двустаен апартамент в квартал Левски",
                            District = "Левски",
                            Features = "2 стаен,Обзаведен,65 кв.м",
                            Floor = 4,
                            Furnished = true,
                            Image = "images/property-2.jpg",
                            Price = 400,
                            PriceUnit = "/ месец",
                            Rooms = 2,
                            Title = "Двустаен",
                            Type = "2-стаен"
                        },
                        new
                        {
                            Id = 6,
                            Area = 95,
                            CreatedAt = new DateTime(2026, 5, 5, 9, 43, 34, 735, DateTimeKind.Utc).AddTicks(9130),
                            Description = "Нов тристаен апартамент в модерен комплекс в Одесос",
                            District = "Одесос",
                            Features = "3 стаен,Необзаведен,95 кв.м",
                            Floor = 5,
                            Furnished = false,
                            Image = "images/property-3.jpg",
                            Price = 600,
                            PriceUnit = "/ месец",
                            Rooms = 3,
                            Title = "Тристаен",
                            Type = "3-стаен"
                        },
                        new
                        {
                            Id = 7,
                            Area = 110,
                            CreatedAt = new DateTime(2026, 5, 5, 9, 43, 34, 735, DateTimeKind.Utc).AddTicks(9134),
                            Description = "Офис площ в бизнес сграда в центъра на града",
                            District = "Център",
                            Features = "3 помещения,Обзаведен,110 кв.м",
                            Floor = 3,
                            Furnished = true,
                            Image = "images/property-1.jpg",
                            Price = 800,
                            PriceUnit = "/ месец",
                            Rooms = 3,
                            Title = "Офис",
                            Type = "Офис"
                        },
                        new
                        {
                            Id = 8,
                            Area = 55,
                            CreatedAt = new DateTime(2026, 5, 5, 9, 43, 34, 735, DateTimeKind.Utc).AddTicks(9138),
                            Description = "Творческо ателие в арт зона на града",
                            District = "Чайка",
                            Features = "Отворен план,Необзаведен,55 кв.м",
                            Floor = 1,
                            Furnished = false,
                            Image = "images/property-2.jpg",
                            Price = 300,
                            PriceUnit = "/ месец",
                            Rooms = 1,
                            Title = "Ателие",
                            Type = "Ателие"
                        },
                        new
                        {
                            Id = 9,
                            Area = 160,
                            CreatedAt = new DateTime(2026, 5, 5, 9, 43, 34, 735, DateTimeKind.Utc).AddTicks(9143),
                            Description = "Роскошен пентхаус с тераса и барбекю зона",
                            District = "Приморски",
                            Features = "4 стаен,Обзаведен,160 кв.м",
                            Floor = 8,
                            Furnished = true,
                            Image = "images/property-3.jpg",
                            Price = 1500,
                            PriceUnit = "/ месец",
                            Rooms = 4,
                            Title = "Пентхаус",
                            Type = "Пентхаус"
                        },
                        new
                        {
                            Id = 10,
                            Area = 58,
                            CreatedAt = new DateTime(2026, 5, 5, 9, 43, 34, 735, DateTimeKind.Utc).AddTicks(9147),
                            Description = "Компактен двустаен в близост до университета",
                            District = "Одесос",
                            Features = "2 стаен,Обзаведен,58 кв.м",
                            Floor = 2,
                            Furnished = true,
                            Image = "images/property-1.jpg",
                            Price = 380,
                            PriceUnit = "/ месец",
                            Rooms = 2,
                            Title = "Двустаен",
                            Type = "2-стаен"
                        },
                        new
                        {
                            Id = 11,
                            Area = 105,
                            CreatedAt = new DateTime(2026, 5, 5, 9, 43, 34, 735, DateTimeKind.Utc).AddTicks(9151),
                            Description = "Панорамен тристаен с изглед към Варненското езеро",
                            District = "Аспарухово",
                            Features = "3 стаен,Обзаведен,105 кв.м",
                            Floor = 7,
                            Furnished = true,
                            Image = "images/property-2.jpg",
                            Price = 700,
                            PriceUnit = "/ месец",
                            Rooms = 3,
                            Title = "Тристаен",
                            Type = "3-стаен"
                        },
                        new
                        {
                            Id = 12,
                            Area = 220,
                            CreatedAt = new DateTime(2026, 5, 5, 9, 43, 34, 735, DateTimeKind.Utc).AddTicks(9154),
                            Description = "Нова къща в затворен комплекс с охрана",
                            District = "Владиславово",
                            Features = "6 стаен,Необзаведен,220 кв.м",
                            Floor = 2,
                            Furnished = false,
                            Image = "images/property-3.jpg",
                            Price = 1800,
                            PriceUnit = "/ месец",
                            Rooms = 6,
                            Title = "Къща",
                            Type = "Къща"
                        });
                });

            modelBuilder.Entity("HomeNest.Data.Models.User", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsAdmin")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("HomeNest.Data.Models.Favorite", b =>
                {
                    b.HasOne("HomeNest.Data.Models.Property", "Property")
                        .WithMany("Favorites")
                        .HasForeignKey("PropertyId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("HomeNest.Data.Models.User", "User")
                        .WithMany("Favorites")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Property");

                    b.Navigation("User");
                });

            modelBuilder.Entity("HomeNest.Data.Models.Property", b =>
                {
                    b.HasOne("HomeNest.Data.Models.User", "Owner")
                        .WithMany("Properties")
                        .HasForeignKey("OwnerId");

                    b.Navigation("Owner");
                });

            modelBuilder.Entity("HomeNest.Data.Models.Property", b =>
                {
                    b.Navigation("Favorites");
                });

            modelBuilder.Entity("HomeNest.Data.Models.User", b =>
                {
                    b.Navigation("Favorites");

                    b.Navigation("Properties");
                });
#pragma warning restore 612, 618
        }
    }
}
